# Generated by Django 4.2.3 on 2023-07-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_content_alter_blog_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="word_count",
            field=models.IntegerField(null=True),
        ),
    ]
